apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: python-run
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
  steps:
  - name: run
    image: python:3
    command:
     - python hello.py
